# Tomcat
server:
  port: 8081
  servlet:
    context-path: /


# Spring
spring:
  application:
    name: ruoyi-gateway
  profiles:
    active: @profiles.active@

# nacos 配置
  cloud:
    nacos:
      server-addr: @nacos.server@
      username: @nacos.username@
      password: @nacos.password@
      discovery:
        group: @nacos.discovery.group@
        namespace: @nacos.namespace@  # 对应你 Nacos 里的命名空间 ID
      config:
        group: @nacos.config.group@
        namespace: @nacos.namespace@
  config:
    import:
      - optional:nacos:application-common.yml
      - optional:nacos:${spring.application.name}.yml
