# Tomcat
server:
  port: 8080
  servlet:
    context-path: /


# Spring
spring:
  application:
    name: ruoyi-gateway
  profiles:
    active: public

# nacos 配置
  cloud:
    nacos:
      server-addr: 10.211.55.19:8848
      username: nacos
      password: nacos
      discovery:
        group: DEFAULT_GROUP
        namespace:  ${spring.profiles.active}  # 对应你 Nacos 里的命名空间 ID
      config:
        group: DEFAULT_GROUP
        namespace:  ${spring.profiles.active}
  config:
    import:
      - optional:nacos:application-common.yml
      - optional:nacos:${spring.application.name}.yml