server:
  port: 9206

spring:
  application:
    name: ruoyi-manager
  profiles:
    active: public

  cloud:
    nacos:
      # nacos 服务地址
      server-addr: 10.211.55.19:8848
      username: nacos
      password: nacos
      discovery:
        # 注册组
        group: DEFAULT_GROUP
        namespace: public
      config:
        # 配置组
        group: DEFAULT_GROUP
        namespace: public
  config:
    import:
      - optional:nacos:application-common.yml
      - optional:nacos:datasource.yml
      - optional:nacos:${spring.application.name}.yml

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    table: flyway_schema_history
