# Tomcat
server:
  port: 9201


# Spring
spring:
  application:
    # 应用名称
    name: ruoyi-system
  profiles:
    # 环境配置
    active: dev

  cloud:
    nacos:
      # nacos 服务地址
      server-addr: 10.211.55.19:8848
      username: nacos
      password: nacos
      discovery:
        # 注册组
        group: DEFAULT_GROUP
        namespace: public
      config:
        # 配置组
        group: DEFAULT_GROUP
        namespace: public
  config:
    import:
      - optional:nacos:application-common.yml
      - optional:nacos:datasource.yml
      - optional:nacos:${spring.application.name}.yml
